"use client";

import { useState } from "react";
import {
  AlertTriangle,
  BookOpen,
  CalendarClock,
  CheckCircle2,
  ClipboardList,
  Compass,
  Copy,
  Cpu,
  Database,
  Gauge,
  GitBranch,
  HelpCircle,
  Lightbulb,
  Printer,
  RotateCcw,
  Search,
  Sigma,
  Tag,
  Target,
} from "lucide-react";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { buildWhatsAppLink } from "@/lib/whatsapp";
import type { BlueprintRequest, BlueprintResult } from "@/lib/blueprint-schema";

const DIFFICULTY_STYLES: Record<BlueprintResult["difficulty"]["level"], string> = {
  Easy: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
  Moderate: "bg-gold-50 text-gold-700 dark:bg-gold-950/40 dark:text-gold-300",
  High: "bg-orange-50 text-orange-700 dark:bg-orange-950/40 dark:text-orange-300",
  "Very High": "bg-red-50 text-red-700 dark:bg-red-950/40 dark:text-red-300",
};

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col gap-4 rounded-2xl border border-border bg-surface p-6 sm:p-7">
      <div className="flex items-center gap-3">
        <span className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-magenta-50 text-magenta-700 dark:bg-magenta-900/30 dark:text-magenta-200">
          <Icon className="h-5 w-5" />
        </span>
        <h2 className="font-display text-xl font-semibold text-foreground">{title}</h2>
      </div>
      {children}
    </section>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="flex flex-col gap-2">
      {items.map((item, i) => (
        <li key={i} className="flex gap-2 text-sm leading-relaxed text-foreground-muted">
          <span className="mt-2 h-1 w-1 flex-shrink-0 rounded-full bg-gold-500" />
          {item}
        </li>
      ))}
    </ul>
  );
}

function buildPlainText(input: BlueprintRequest, r: BlueprintResult): string {
  const lines: string[] = [
    `SCRIBIA RESEARCH BLUEPRINT`,
    `Topic: ${input.topic}`,
    "",
    "1. RESEARCH OVERVIEW",
    r.overview,
    "",
    `2. RESEARCH DIFFICULTY: ${r.difficulty.level}`,
    r.difficulty.explanation,
    "",
    `3. SUGGESTED RESEARCH DESIGN: ${r.researchDesign.design}`,
    r.researchDesign.rationale,
    "",
    "4. SUGGESTED OBJECTIVES",
    ...r.objectives.map((o, i) => `${i + 1}. ${o}`),
    "",
    "5. SUGGESTED RESEARCH QUESTIONS",
    ...r.researchQuestions.map((q, i) => `${i + 1}. ${q}`),
    "",
  ];

  if (r.hypotheses.applicable && r.hypotheses.items.length > 0) {
    lines.push("6. SUGGESTED HYPOTHESES", ...r.hypotheses.items.map((h, i) => `${i + 1}. ${h}`), "");
  }

  lines.push(
    "7. POSSIBLE VARIABLES",
    `Independent: ${r.variables.independent.join(", ") || "N/A"}`,
    `Dependent: ${r.variables.dependent.join(", ") || "N/A"}`,
    `Moderating: ${r.variables.moderating.join(", ") || "N/A"}`,
    `Mediating: ${r.variables.mediating.join(", ") || "N/A"}`,
    `Control: ${r.variables.control.join(", ") || "N/A"}`,
    "",
    "8. RECOMMENDED DATA COLLECTION METHODS",
    ...r.dataCollectionMethods.map((m) => `- ${m.method}: ${m.explanation}`),
    "",
    "9. RECOMMENDED DATA ANALYSIS SOFTWARE",
    ...r.analysisSoftware.map((s) => `- ${s.software}: ${s.reason}`),
    "",
    "10. SUGGESTED STATISTICAL TESTS",
    r.statisticalTests.join(", "),
    "",
    "11. SUGGESTED KEYWORDS",
    r.keywords.join(", "),
    "",
    "12. SUGGESTED SEARCH TERMS",
    ...r.searchTerms.map((s) => `"${s}"`),
    "",
    "13. RECOMMENDED ACADEMIC DATABASES",
    r.databases.join(", "),
    "",
    "14. POSSIBLE CHALLENGES",
    ...r.challenges.map((c) => `- ${c.challenge}: ${c.note}`),
    "",
    "15. SUGGESTED TIMELINE",
    ...r.timeline.map((t) => `- ${t.phase} (${t.duration}): ${t.description}`),
    "",
    "16. SUCCESS TIPS",
    ...r.successTips.map((t, i) => `${i + 1}. ${t}`),
    "",
    "Generated by SCRIBIA Research Blueprint - a planning roadmap, not a written project. For hands-on writing and analysis support, contact SCRIBIA Writing Services."
  );

  return lines.join("\n");
}

export function BlueprintReport({
  input,
  result,
  onReset,
}: {
  input: BlueprintRequest;
  result: BlueprintResult;
  onReset: () => void;
}) {
  const [copied, setCopied] = useState(false);

  async function handleCopy() {
    await navigator.clipboard.writeText(buildPlainText(input, result));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handlePrint() {
    window.print();
  }

  const whatsappMessage = `Hello SCRIBIA Writing Services, I generated a Research Blueprint for my topic: "${input.topic}" and I'd like professional help taking it forward.`;

  return (
    <div className="mx-auto flex max-w-4xl flex-col gap-6">
      <div className="no-print flex flex-wrap items-center justify-between gap-3">
        <Button variant="ghost" size="sm" onClick={onReset}>
          <RotateCcw className="h-4 w-4" />
          New Blueprint
        </Button>
        <div className="flex flex-wrap items-center gap-3">
          <Button variant="outline" size="sm" onClick={handleCopy}>
            <Copy className="h-4 w-4" />
            {copied ? "Copied!" : "Copy"}
          </Button>
          <Button variant="outline" size="sm" onClick={handlePrint}>
            <Printer className="h-4 w-4" />
            Download PDF
          </Button>
        </div>
      </div>

      <div className="print-area flex flex-col gap-6">
        <div className="flex flex-col gap-4 rounded-2xl border border-gold-400/40 bg-surface-muted p-6 sm:p-8">
          <span className="text-xs font-semibold uppercase tracking-[0.2em] text-magenta-700 dark:text-magenta-300">
            SCRIBIA Research Blueprint
          </span>
          <h1 className="font-display text-2xl font-semibold leading-snug text-foreground sm:text-3xl">
            {input.topic}
          </h1>
          <div className="flex flex-wrap items-center gap-2">
            {input.academicLevel && <Badge>{input.academicLevel}</Badge>}
            {input.researchType && <Badge>{input.researchType}</Badge>}
            {input.faculty && <Badge>{input.faculty}</Badge>}
            {input.department && <Badge>{input.department}</Badge>}
          </div>
        </div>

        <Section icon={BookOpen} title="Research Overview">
          <p className="text-sm leading-relaxed text-foreground-muted">{result.overview}</p>
        </Section>

        <Section icon={Gauge} title="Research Difficulty">
          <div className="flex flex-col gap-3">
            <span
              className={`w-fit rounded-full px-4 py-1.5 text-sm font-semibold ${DIFFICULTY_STYLES[result.difficulty.level]}`}
            >
              {result.difficulty.level}
            </span>
            <p className="text-sm leading-relaxed text-foreground-muted">{result.difficulty.explanation}</p>
          </div>
        </Section>

        <Section icon={Compass} title="Suggested Research Design">
          <div className="flex flex-col gap-2">
            <span className="font-display text-lg font-semibold text-magenta-700 dark:text-magenta-300">
              {result.researchDesign.design}
            </span>
            <p className="text-sm leading-relaxed text-foreground-muted">{result.researchDesign.rationale}</p>
          </div>
        </Section>

        <Section icon={Target} title="Suggested Objectives">
          <BulletList items={result.objectives} />
        </Section>

        <Section icon={HelpCircle} title="Suggested Research Questions">
          <BulletList items={result.researchQuestions} />
        </Section>

        {result.hypotheses.applicable && result.hypotheses.items.length > 0 && (
          <Section icon={Lightbulb} title="Suggested Hypotheses">
            <BulletList items={result.hypotheses.items} />
            {result.hypotheses.note && (
              <p className="text-xs italic text-foreground-muted">{result.hypotheses.note}</p>
            )}
          </Section>
        )}

        <Section icon={GitBranch} title="Possible Variables">
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {[
              ["Independent Variable(s)", result.variables.independent],
              ["Dependent Variable(s)", result.variables.dependent],
              ["Moderating Variable(s)", result.variables.moderating],
              ["Mediating Variable(s)", result.variables.mediating],
              ["Control Variables", result.variables.control],
            ]
              .filter(([, list]) => (list as string[]).length > 0)
              .map(([label, list]) => (
                <div key={label as string} className="flex flex-col gap-1.5">
                  <span className="text-xs font-semibold uppercase tracking-wide text-gold-600 dark:text-gold-400">
                    {label as string}
                  </span>
                  <span className="text-sm text-foreground-muted">{(list as string[]).join(", ")}</span>
                </div>
              ))}
          </div>
        </Section>

        <Section icon={ClipboardList} title="Recommended Data Collection Methods">
          <div className="flex flex-col gap-3">
            {result.dataCollectionMethods.map((m) => (
              <div key={m.method} className="rounded-xl border border-border p-4">
                <span className="font-display font-semibold text-foreground">{m.method}</span>
                <p className="mt-1 text-sm leading-relaxed text-foreground-muted">{m.explanation}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section icon={Cpu} title="Recommended Data Analysis Software">
          <div className="flex flex-col gap-3">
            {result.analysisSoftware.map((s) => (
              <div key={s.software} className="rounded-xl border border-border p-4">
                <span className="font-display font-semibold text-foreground">{s.software}</span>
                <p className="mt-1 text-sm leading-relaxed text-foreground-muted">{s.reason}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section icon={Sigma} title="Suggested Statistical Tests">
          <div className="flex flex-wrap gap-2">
            {result.statisticalTests.map((t) => (
              <Badge key={t}>{t}</Badge>
            ))}
          </div>
        </Section>

        <Section icon={Tag} title="Suggested Keywords">
          <div className="flex flex-wrap gap-2">
            {result.keywords.map((k) => (
              <span
                key={k}
                className="rounded-full border border-border px-3 py-1 text-xs text-foreground-muted"
              >
                {k}
              </span>
            ))}
          </div>
        </Section>

        <Section icon={Search} title="Suggested Search Terms">
          <div className="flex flex-col gap-2">
            {result.searchTerms.map((s) => (
              <span key={s} className="text-sm text-foreground-muted">
                &ldquo;{s}&rdquo;
              </span>
            ))}
          </div>
        </Section>

        <Section icon={Database} title="Recommended Academic Databases">
          <div className="flex flex-wrap gap-2">
            {result.databases.map((d) => (
              <Badge key={d}>{d}</Badge>
            ))}
          </div>
        </Section>

        <Section icon={AlertTriangle} title="Possible Challenges">
          <div className="flex flex-col gap-3">
            {result.challenges.map((c) => (
              <div key={c.challenge} className="rounded-xl border border-border p-4">
                <span className="font-display font-semibold text-foreground">{c.challenge}</span>
                <p className="mt-1 text-sm leading-relaxed text-foreground-muted">{c.note}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section icon={CalendarClock} title="Suggested Timeline">
          <div className="flex flex-col gap-3">
            {result.timeline.map((t) => (
              <div key={t.phase} className="flex flex-col gap-1 border-l-2 border-gold-400 pl-4">
                <div className="flex flex-wrap items-baseline gap-2">
                  <span className="font-display font-semibold text-foreground">{t.phase}</span>
                  <span className="text-xs font-medium uppercase tracking-wide text-gold-600 dark:text-gold-400">
                    {t.duration}
                  </span>
                </div>
                <p className="text-sm leading-relaxed text-foreground-muted">{t.description}</p>
              </div>
            ))}
          </div>
        </Section>

        <Section icon={CheckCircle2} title="Success Tips">
          <BulletList items={result.successTips} />
        </Section>

        <div className="no-print relative overflow-hidden rounded-2xl bg-magenta-900 p-8 text-white sm:p-10">
          <div
            aria-hidden
            className="pointer-events-none absolute -right-16 -top-16 h-56 w-56 rounded-full bg-gold-500/10 blur-3xl"
          />
          <div className="relative flex flex-col gap-5">
            <h2 className="font-display text-2xl font-semibold">Need Professional Assistance?</h2>
            <p className="text-magenta-100/90">SCRIBIA Writing Services can help with:</p>
            <ul className="grid grid-cols-1 gap-2 text-sm text-magenta-50 sm:grid-cols-2">
              {[
                "Proposal Writing",
                "Journal Articles",
                "Data Analysis",
                "Editing",
                "Supervisor Corrections",
                "Referencing",
                "Presentations",
              ].map((item) => (
                <li key={item} className="flex items-center gap-2">
                  <span className="h-1 w-1 rounded-full bg-gold-400" />
                  {item}
                </li>
              ))}
            </ul>
            <div className="flex flex-col gap-3 pt-2 sm:flex-row">
              <Button href="/pricing" variant="primary" size="lg">
                Get a Personalized Quote
              </Button>
              <Button href={buildWhatsAppLink(whatsappMessage)} variant="whatsapp" size="lg" external>
                Chat on WhatsApp
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
